version: "3.8"

services:
  discord-bot:
    restart: unless-stopped
    container_name: discord-bot
    build:
      context: .
      dockerfile: src/DiscordBot.Api/Dockerfile
    environment:
      TOKEN:
  voice-channel-manager-database:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "voice-channel-manager"
      POSTGRES_PASSWORD: "123456"
    ports:
      - 15432:5432