version: "3.8"

services:
  application:
    restart: unless-stopped
    container_name: discord-bot
    build:
      context: .
      dockerfile: src/DiscordBot.Api/Dockerfile
    environment:
      TOKEN:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: voice-channel-manager
      POSTGRES_PASSWORD: 123456
    ports:
      - 15432:5432
  cache:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --save "" --appendonly no --requirepass password
    ports:
      - '6369:6379'